runtime: python38
instance_class: F4
entrypoint: gunicorn main:app --workers 1 --threads 1 -c /config/gunicorn.py

handlers:
- url: /favicon.ico
  static_files: ezra/static/favicon.svg
  upload: ezra/static/favicon.svg

- url: /robot.txt
  static_files: ezra/static/robot.txt
  upload: ezra/static/robot.txt

- url: /google61ad13e8b605dad5.html
  static_files: ezra/static/google61ad13e8b605dad5.html
  upload: ezra/static/google61ad13e8b605dad5.html

- url: /static
  static_dir: ezra/static

- url: /api/(.*\.(html|yaml|js|css|png))$
  static_files: ezra/static/api/\1
  upload: ezra/static/api/.*

- url: /api$
  static_files: ezra/static/api/redirect.html
  upload: ezra/static/api/redirect.html
